# Generated by Django 3.2.23 on 2024-01-18 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_newuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
