# Generated by Django 3.2.23 on 2024-01-18 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_newuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
