# Generated by Django 3.2.23 on 2024-01-18 01:34

from django.db import migrations, models
import utils.validator.validator


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[utils.validator.validator.validate_email]),
        ),
    ]
